/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.pkg3.pkg7a.controlnumerico;

import static e.pkg3.pkg7a.controlnumerico.controlNumerico.LOGGER;
import java.io.IOException;
import java.util.logging.ConsoleHandler;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel Cañamaque
 */
public class controlNumerico extends javax.swing.JFrame {
    static final Logger LOGGER = Logger.getLogger("controlnumerico.controlNumerico");
    int posicion1;
    int posicion2;
    int numero1;
    int numero2;
    double division;
    boolean error;
    FileHandler filetxt;
    
//    ConsoleHandler consoletxt;
    
    
    /**
     * Creates new form controlNumerico
     */
    public controlNumerico() {
        initComponents();
        
        try {
            filetxt = new FileHandler("Logging.log");
            SimpleFormatter formatterTxt = new SimpleFormatter();
            filetxt.setFormatter(formatterTxt);
        } catch (IOException ex) {
            Logger.getLogger(controlNumerico.class.getName()).log(Level.SEVERE, null, ex);        
        }
        
        LOGGER.setLevel(Level.FINEST);
        LOGGER.addHandler(filetxt);
        
        
//        consoletxt = new ConsoleHandler();
//        consoletxt.setLevel(Level.FINEST);
//        
//        LOGGER.addHandler(consoletxt);
//        
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        texto1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texto3 = new javax.swing.JTextField();
        texto2 = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduzca una serie de números:");

        jLabel2.setText("Introduzca la posición de uno de los números:");

        jLabel3.setText("Introduzca la posición de otro de los números:");

        calcular.setText("Dividir el primer número entre el segundo número");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto1)
                    .addComponent(texto2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(texto3)
                            .addComponent(resultado))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        String secuencia=texto1.getText();
        
        try{
            posicion1=Integer.valueOf(texto2.getText())-1;
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Introduce un Numero en el campo 1");
            LOGGER.finest("Error en el campo de posicion 1");
            error=true;
        }
        
        try{
            posicion2=Integer.valueOf(texto3.getText())-1;
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Introduce un Numero en el campo 2");
            LOGGER.severe("Error en el campo de posicion 2");
            error=true;
        }       
        
        try{
            numero1=secuencia.charAt(posicion1)-'0';
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No existe la posición indicada en el campo 1");
            LOGGER.warning("Error, la posicion indicada en el campo 1 no existe");
            error=true;
        }
        
        try{
            numero2=secuencia.charAt(posicion2)-'0';
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No existe la posición indicada en el campo 2");
            LOGGER.warning("Error, la posicion indicada en el campo 2 no existe");
            error=true;
        }
        
        if (numero2==0){
            JOptionPane.showMessageDialog(this, "No se puede dividir entre 0");
            LOGGER.info("Error, no se puede divir por 0");
            error=true;
        }
        if(error==false){
            division = (double)numero1/(double)numero2;
            resultado.setText(""+division);
        }
        
        
        error=false;
        
        
    }//GEN-LAST:event_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controlNumerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controlNumerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controlNumerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controlNumerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new controlNumerico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField resultado;
    private javax.swing.JTextField texto1;
    private javax.swing.JTextField texto2;
    private javax.swing.JTextField texto3;
    // End of variables declaration//GEN-END:variables
}
